config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope :user do
    devise_for :users
    get 'profile', to: 'devise/registrations#edit'
  end
  root "home#index"
  resources :films do
    collection do
      get 'search'
    end
  end
  resources :categories
  resources :countries
  resources :genres
  resources :people
  resources :tags
  resources :seasons
  resources :episodes
  resources :comments
  resources :watch_items, only: %i(create destroy update)
end

app/models/season.rb
# == Schema Information
#
# Table name: seasons
#
#  id           :bigint           not null, primary key
#  film_id      :bigint           not null
#  title        :string           not null
#  description  :text
#  release_date :datetime         not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Season < ApplicationRecord
  belongs_to :film
  has_many :episode, dependent: :destroy

  validates :title, presence: true, length: { in: 1..100 }
  validates :description, length: { in: 1..300 }, allow_blank: true
  validates_date :release_date, presence: true, between: ['01.01.1800', :today]

  def approved?
    film&.approved?
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @film = Film.find(params[:film_id])
    authorize(@film, :show?)
    @seasons = policy_scope(@film.seasons)
  end

  def show
    @season = Season.find(params[:id])
    authorize(@season, :show?)
    @film = @season.film
    authorize(@film, :show?)
    @episodes = policy_scope(@season.episode)
  end

  def new
    @film = Film.find(params[:film_id])
    authorize(@film, :edit?)
    @season = @film.seasons.new
  end

  def create
    @film = Film.find(params[:film_id])
    authorize(@film, :edit?)
    @season = @film.seasons.new(season_params)

    if @season.save
      redirect_to @season
    else
      render :new
    end
  end

  def edit
    @season = Season.find(params[:id])
    authorize(@season.film, :edit?)
  end

  def update
    @season = Season.find(params[:id])
    authorize(@season.film, :edit?)

    if @season.update(season_params)
      redirect_to @season
    else
      render :edit
    end
  end

  def destroy
    @season = Season.find(params[:id])
    authorize(@season.film, :edit?)
    film_id = @season.film_id
    @season.destroy!

    redirect_to seasons_path(film_id)
  end

  private

  def season_params
    params.require(:season).permit(:title, :description, :release_date)
  end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_with model: season do |form| %>
  <div>
    <%= hidden_field_tag :film_id, film_id %>
  </div>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% season.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
    <% season.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :release_date %><br>
    <%= form.text_field :release_date, class: "form-control", "data-provide" => 'datepicker', 'data-date-format' => 'dd.mm.yyyy' %><br>
    <% season.errors.full_messages_for(:release_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Edit season</h1>

<%= render "form", season: @season, film_id: @season.film.id  %>

app/views/seasons/index.html.erb
<h2><%= link_to "#{@film.title}", film_path(@film) %></h2>
<% if policy(@film).edit? %>
  <%= link_to 'Create season', new_season_path(film_id: @film.id), class: 'btn btn-primary' %>
<% end %>
<h2>Seasons list:</h2>
<ul>
  <% @seasons.each do |season| %>
    <li>
      <h4><%= link_to "#{season.title}", season_path(season) %></h4>
    </li>
  <% end %>
</ul>

app/views/seasons/new.html.erb
<h1>Create season</h1>

<%= render "form", season: @season, film_id: @film.id %>

app/views/seasons/show.html.erb
<h2><%= link_to "#{@film.title}", film_path(@film) %></h2>
<h1><%= @season.title %></h1>
<h4><%= link_to 'Go to seasons list', seasons_path(film_id: @film.id) %></h4>
<% if policy(@film).edit? %>
  <%= link_to "Edit", edit_season_path(@season), class: 'btn btn-primary' %></li>
  <%= link_to "Destroy", season_path(@season), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } %></li>
<% end %>
<p><%= @season.description %></p>
<p><%= @season.release_date.year %></p>
<p>Episodes list:</p>
<% if policy(@film).edit? %>
  <%= link_to "Add episode", new_episode_path(season_id: @season.id), class: 'btn btn-primary' %></li>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @season.episode.each do |episode| %>
      <tr>
        <td>picture</td>
        <td><%= link_to "#{episode.title}", episode_path(episode) %></td>
        <td><%= episode.description %></td>
        <td>
          <% if policy(@film).edit? %>
            <%= link_to "Edit", edit_episode_path(episode), class: 'btn btn-primary' %>
            <%= link_to "Destroy", episode_path(episode), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>