config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope :user do
    devise_for :users
    get 'profile', to: 'devise/registrations#edit'
  end
  root "home#index"
  resources :films do
    collection do
      get 'search'
    end
  end
  resources :categories
  resources :countries
  resources :genres
  resources :people
  resources :tags
  resources :seasons
  resources :episodes
  resources :comments
  resources :watch_items, only: %i(create destroy update)
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id              :bigint           not null, primary key
#  title           :string           not null
#  description     :text
#  trailer_url     :text
#  release_date    :datetime         default(Tue, 01 Jan 1895 00:00:00.000000000 UTC +00:00), not null
#  duration        :integer          not null
#  age_restriction :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  creator_id      :bigint
#  approved        :boolean          default(FALSE), not null
#
require 'uri'

class Film < ApplicationRecord
  belongs_to :creator, class_name: 'User', optional: true

  has_many :film_categories, dependent: :destroy
  has_many :categories, through: :film_categories
  has_many :film_countries, dependent: :destroy
  has_many :countries, through: :film_countries
  has_many :film_genres, dependent: :destroy
  has_many :genres, through: :film_genres
  has_many :film_people, dependent: :destroy
  has_many :people, through: :film_people
  has_many :film_tags, dependent: :destroy
  has_many :tags, through: :film_tags
  has_many :seasons, dependent: :destroy
  has_many :watch_items, dependent: :destroy
  has_many :users, through: :watch_items
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true, length: { in: 1..100 }
  validates :description, presence: true, length: { in: 10..500 }
  validates :trailer_url, format: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/, allow_blank: true
  validates_date :release_date, between: ['01.01.1895', :today]
  validates :duration,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 3, less_than_or_equal_to: 600 }
  validates :age_restriction,
            presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 21 }

  accepts_nested_attributes_for :film_categories, :film_genres, :film_tags, :film_countries, :film_people,
                                allow_destroy: true

  self.per_page = 15

  attr_writer :tags_string, :countries_string, :actors_string, :directors_string

  def tags_string
    tags.map(&:name).join(', ')
  end

  def countries_string
    countries.map(&:name).join(', ')
  end

  def actors_string
    names = film_people.where(role: 'Actor').map do |film_person|
      film_person.person.name
    end
    names.join(', ')
  end

  def directors_string
    names = film_people.where(role: 'Director').map do |film_person|
      film_person.person.name
    end
    names.join(', ')
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  include FilmAttributes

  def index
    @films = policy_scope(Film.paginate(page: params[:page]))
  end

  def show
    @film = Film.find(params[:id])
    authorize(@film)
  end

  def new
    @film = Film.new
    authorize(@film)
  end

  def create
    @film = Film.new(film_params)
    assign_film_attributes
    authorize(@film)

    if @film.save
      redirect_to @film
    else
      render :new
    end
  end

  def edit
    @film = Film.find(params[:id])
    authorize(@film)
  end

  def update
    @film = Film.find(params[:id])
    assign_film_attributes
    authorize(@film)

    if @film.update(film_params)
      redirect_to @film
    else
      render :edit
    end
  end

  def destroy
    @film = Film.find(params[:id])
    authorize(@film)
    @film.destroy!

    redirect_to films_path
  end

  def search
    @films = Film.where('title ILIKE ?', "%#{params[:keyword]}%").paginate(page: params[:page])
    @keyword = params[:keyword]
    authorize(Film.new)
  end

  private

  def film_params
    params.require(:film).permit(:title, :description, :trailer_url, :release_date, :duration,
                                 :age_restriction, :creator_id, :tags_string, :countries_string,
                                 :actors_string, :directors_string, :approved)
  end

  def assign_film_attributes
    @film.assign_attributes(
      film_categories_attributes: film_categories_attributes,
      film_genres_attributes: film_genres_attributes,
      film_tags_attributes: film_tags_attributes,
      film_countries_attributes: film_countries_attributes,
      film_people_attributes: film_people_attributes,
      creator_id: current_user.id
    )
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Picture</th>
      <th scope="col">Title</th>
      <th scope="col">Year</th>
      <th scope="col">Categories</th>
      <th scope="col">Genres</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% films.each do |film| %>
      <tr>
        <td><%='film.picture'%></td>
        <td><%= link_to film.title, film_path(film) %></td>
        <td><%=film.release_date.year%></td>
        <td><%=film.categories.map(&:name).join(', ') %></td>
        <td><%=film.genres.map(&:name).join(', ')%></td>
        <td>
          <% if policy(film).edit? %>
            <%= link_to "Edit", edit_film_path(film), class: 'btn btn-primary' %>
          <% end %>
          <% if policy(film).destroy? %>
            <%= link_to "Destroy", film_path(film), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
          <% end %>
          <% if current_user.present? && (current_user.admin? || current_user.editor?) %>
            <% if film.approved? %>
              <button type="button" class="btn btn-success">Approved</button>
            <% else %>
              <button type="button" class="btn btn-secondary">Unapproved</button>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center-container">
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info films %>
    </div>
    <%= will_paginate films, :container => false %>
  </div>
</div>

app/views/films/_form.html.erb
<%= form_with model: film do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
    <% film.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %><br>
    <% film.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :trailer_url %><br>
    <%= form.text_area :trailer_url, class: "form-control" %><br>
    <% film.errors.full_messages_for(:trailer_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :release_date %><br>
    <%= form.text_field :release_date, class: "form-control", "data-provide" => 'datepicker', 'data-date-format' => 'dd.mm.yyyy' %><br>
    <% film.errors.full_messages_for(:release_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :duration %><br>
    <%= form.text_area :duration, class: "form-control" %><br>
    <% film.errors.full_messages_for(:duration).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :age_restriction %><br>
    <%= form.text_area :age_restriction, class: "form-control" %><br>
    <% film.errors.full_messages_for(:age_restriction).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :categories %><br>
    <% Category.all.each do |category| %>
      <li>
        <%= check_box_tag("categories[]", category.id, film.category_ids.include?(category.id)) %>
        <%= label_tag(category.name) %>
      </li>
    <% end %>
  </div>

  <div>
    <%= form.label :genres %><br>
    <% Genre.all.each do |genre| %>
      <li>
        <%= check_box_tag("genres[]", genre.id, film.genre_ids.include?(genre.id)) %>
        <%= label_tag(genre.name) %>
      </li>
    <% end %>
  </div>

  <div>
    <%= form.label :tags %><br>
    <%= form.text_field :tags_string, class: "form-control" %><br>
    <% film.errors.full_messages_for(:tags).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :countries %><br>
    <%= form.text_field :countries_string, class: "form-control" %><br>
    <% film.errors.full_messages_for(:countris).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label 'Actors' %><br>
    <%= form.text_field :actors_string, class: "form-control" %><br>
    <%= form.label 'Directors' %><br>
    <%= form.text_field :directors_string, class: "form-control" %><br>
    <% film.errors.full_messages_for(:person).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% if current_user.admin? %>
    <div>
      <%= form.label 'Status' %><br>
      <%= form.check_box(:approved) %>
      <%= label_tag('Approved') %>
    </div>
  <% end %>

  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/films/edit.html.erb
<h1>Edit film</h1>
<%= render "form", film: @film %>

app/views/films/index.html.erb
<h1 class="text-center">List of films</h1>
<br>
<%= render "film_list", films: @films %>

app/views/films/new.html.erb
<h1>Create film</h1>
<%= render "form", film: @film %>

app/views/films/search.html.erb
<h1> Search results for "<%= @keyword %>"</h1>
<%= render "film_list", films: @films %>

app/views/films/show.html.erb
<h1 class="text-center">
  <%= @film.title %>
</h1>
<ul>
  <p>
    <% if policy(@film).edit? %>
      <%= link_to "Edit", edit_film_path(@film), class: 'btn btn-primary' %>
    <% end %>
    <% if policy(@film).destroy? %>
      <%= link_to "Destroy", film_path(@film), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    <% end %>
    <% if current_user.present? && (current_user.admin? || current_user.editor?) %>
      <% if @film.approved? %>
        <button type="button" class="btn btn-success">Approved</button>
      <% else %>
        <button type="button" class="btn btn-secondary">Unapproved</button>
      <% end %>
    <% end %>
  </p>
  <p>
    Description:
    <%= @film.description %>
  </p>
  <p>
    Trailer:
    <%= @film.trailer_url %>
  </p>
  <p>
    Relese date:
    <%= @film.release_date %>
  </p>
  <p>
    Duration:
    <%= @film.duration %>
  </p>
  <p>
    Age restriction:
    <%= @film.age_restriction %>
  </p>  
  <p>
    Categories:
    <% @film.categories.each do |record| %>
      <%= record.name %>
    <% end %>
  </p>
  <p>
    Countries:
    <% @film.countries.each do |record| %>
      <%= record.name %>
      <%= record.banner %>
    <% end %>
  </p>
  <p>
    Genres:
    <% @film.genres.each do |record| %>
      <%= record.name %>
    <% end %>
  </p>
  <p>
    Tags:
    <% @film.tags.each do |record| %>
      <%= record.name %>
    <% end %>
  </p>
  <p>
    Directors:
    <% @film.film_people.each do |record| %>
      <%= Person.find(record.person_id).name if record.role == 'Director' %>
    <% end %>
  </p>
  <p>
    Actors:
    <% @film.film_people.each do |record| %>
      <%= Person.find(record.person_id).name if record.role == 'Actor' %>
    <% end %>
  </p>
    <% if current_user.present? %>
      <p>
        <% watch_list_record = current_user.watch_items.find_by(film_id: @film.id) %>
        <% unless watch_list_record %>
          <%= link_to 'Add to watching', watch_items_path(film_id: @film.id, user_id: current_user.id, status: 'watching'), method: :post, class: 'btn btn-success' %>
          <%= link_to 'Add to viewed', watch_items_path(film_id: @film.id, user_id: current_user.id, status: 'viewed'), method: :post, class: 'btn btn-success' %>
          <%= link_to 'Will watch', watch_items_path(film_id: @film.id, user_id: current_user.id, status: 'will_watch'), method: :post, class: 'btn btn-success' %>
        <% else %>
          <% unless watch_list_record.status == 'watching' %>
            <%= link_to 'Transfer into watching', watch_item_path(watch_list_record, status: 'watching'), method: :put, class: 'btn btn-success' %>
          <% else %>
            <button type="button" class="btn btn-secondary">Watching</button>
          <% end %>
          <% unless watch_list_record.status == 'viewed' %>
            <%= link_to 'Transfer into viewed', watch_item_path(watch_list_record, status: 'viewed'), method: :put, class: 'btn btn-success' %>
          <% else %>
            <button type="button" class="btn btn-secondary">Viewed</button>
          <% end %>
          <% unless watch_list_record.status == 'will_watch' %>
            <%= link_to "Transfer into 'will watch'", watch_item_path(watch_list_record, status: 'will_watch'), method: :put, class: 'btn btn-success' %>
          <% else %>
            <button type="button" class="btn btn-secondary">Will watch</button>
          <% end %>
        <% end %>
      </p>
    <% end %>
  <p>
    <% if !@film.seasons.size.zero? %>
      <%= link_to 'Show seasons:', seasons_path(film_id: @film.id) %>
      <% @film.seasons.each do |season| %>
        <%= link_to "#{season.title}", season_path(season.id)  %>
      <% end %>
    <% end %>
  </p>
  <p>
    <% if policy(@film).edit? %>
      <%= link_to 'Create season', new_season_path(film_id: @film.id), class: 'btn btn-primary' %>
    <% end %>
  </p>
</ul>
<%= render 'layouts/comments', commentable: @film%>