config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_scope :user do
    devise_for :users
    get 'profile', to: 'devise/registrations#edit'
  end
  root "home#index"
  resources :films do
    collection do
      get 'search'
    end
  end
  resources :categories
  resources :countries
  resources :genres
  resources :people
  resources :tags
  resources :seasons
  resources :episodes
  resources :comments
  resources :watch_items, only: %i(create destroy update)
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  has_many :film_tags, dependent: :destroy
  has_many :films, through: :film_tags

  validates :name, presence: true, length: { in: 1..20 }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = policy_scope(Tag.all)
    authorize(Tag.new)
  end

  def new
    @tag = Tag.new
    authorize(@tag)
  end

  def create
    @tag = Tag.new(tag_params)
    authorize(@tag)

    if @tag.save
      redirect_to tags_path
    else
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    authorize(@tag)
  end

  def update
    @tag = Tag.find(params[:id])
    authorize(@tag)

    if @tag.update(tag_params)
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    authorize(@tag)
    @tag.destroy!

    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with model: tag do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% tag.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit tag</h1>

<%= render "form", tag: @tag %>

app/views/tags/index.html.erb
<h1 class="text-center">Tags list</h1>
<% if policy(Tag.new).new? %>
  <%= link_to "Create tag", new_tag_path, class: 'btn btn-primary' %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Created at</th>
      <th scope="col">Updated at</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%=tag.id%></td>
        <td><%=tag.name%></td>
        <td><%=tag.created_at%></td>
        <td><%=tag.updated_at%></td>
        <td>
          <% if policy(tag).edit? %>
            <%= link_to "Edit", edit_tag_path(tag), class: 'btn btn-primary' %>
          <% end %>
          <% if policy(tag).edit? %>
            <%= link_to "Destroy", tag_path(tag), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1>Create tag</h1>

<%= render "form", tag: @tag %>